# Generated by Django 3.0.4 on 2020-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=8)),
                ('pname', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=6)),
                ('paddress', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=13)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
    ]
