# Generated by Django 3.0.4 on 2020-04-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policeApp', '0001_initial'),
        ('mainApp', '0004_policedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firid', models.CharField(max_length=36)),
                ('content', models.CharField(max_length=1500)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('submissiondate', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('policestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policeApp.PoliceStation')),
                ('userdetailobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.UserDeatil')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=36)),
                ('efile', models.FileField(upload_to='evidence')),
                ('fid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.FIR')),
            ],
        ),
    ]
