# Generated by Django 3.0.4 on 2020-04-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_evidence_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionid', models.CharField(max_length=36)),
                ('content', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=30)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.FIR')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.UserDeatil')),
            ],
        ),
    ]
