# Generated by Django 3.0.4 on 2020-04-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_actionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='efile',
            field=models.FileField(blank=True, null=True, upload_to='evidence'),
        ),
    ]
